---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolution/public_html/cc.aywsolution.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolution/web_cc/
      - /bin/rsync -av ./ $DEPLOYPATH